const docs = [
  {
    type: 'doc',
    id: 'welcome',
    label: 'Welcome',
  },
  {
    type: 'category',
    collapsible: true,
    label: 'Main Concepts',
    items: [
      'main-concepts-introduction',
      'main-concepts-folder-structure',
      'main-concepts-best-practices',
      'main-concepts-scripts',
      'main-concepts-credentials',
      'main-concepts-theme',
      'main-concepts-threekit-config',
      'main-concepts-player-config',
    ],
  },
  {
    type: 'category',
    // id: 'quick-start-new-project',
    collapsible: true,
    label: 'Tutorial',
    items: [
      'tutorial-setup',
      'tutorial-player',
      'tutorial-form',
      'tutorial-widgets',
      'tutorial-multi-products',
      'tutorial-embedding',
    ],
  },
  {
    type: 'category',
    collapsible: true,
    label: 'Components',
    items: [
      'components-overview',
      'components-threekit-provider',
      'components-treble-app',
      'components-product-layout',
      'components-player',
      {
        type: 'category',
        collapsible: false,
        label: 'Forms',
        items: ['forms-overview', 'forms-flat-form'],
      },
      {
        type: 'category',
        collapsible: false,
        label: 'Form Components',
        items: [
          'form-components-overview',
          'form-components-cards',
          'form-components-tiles',
          'form-components-tiles-group',
          'form-components-strips',
        ],
      },
      {
        type: 'category',
        collapsible: false,
        label: 'Widgets',
        items: [
          'widgets-overview',
          'widgets-share',
          'widgets-zoom',
          'widgets-snapshots',
        ],
      },
      {
        type: 'category',
        collapsible: false,
        label: 'Wrappers',
        items: [
          'wrappers-overview',
          'wrappers-await-threekit-load',
          'wrappers-portal-to-element',
        ],
      },
      {
        type: 'category',
        collapsible: false,
        label: 'Layouts',
        items: [
          'layouts-overview',
          'layouts-drawer',
          'layouts-modal',
          'layouts-accordion',
          'layouts-tabs',
        ],
      },
      {
        type: 'category',
        collapsible: false,
        label: 'Displays',
        items: [
          'display-overview',
          'display-product-name',
          'display-product-description',
          'display-attribute-title',
          'display-attribute-value',
          'display-total-price',
        ],
      },
    ],
  },
  {
    type: 'category',
    collapsible: true,
    label: 'Hooks',
    items: [
      'hooks-overview',
      'hooks-use-player-portal',
      'hooks-use-attribute',
      'hooks-use-configurator',
      'hooks-use-name',
      'hooks-use-metadata',
      'hooks-use-price',
      'hooks-use-snapshot',
      'hooks-use-zoom',
      'hooks-use-threekit-init-status',
      'hooks-use-player-loading-status',
    ],
  },
  'treble-js-treble-api',
];

module.exports = { docs };
