name: Publish Packages

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Install dependencies
        run: |
          npm i
          npx lerna bootstrap

      - name: Run build # Run tests of all packages
        run: npx lerna build

      - name: Publish # Run tests of all packages
        run: npx lerna publish --canary --yes
