# repurposed https://dev.to/xaviercanchal/automatic-versioning-in-a-lerna-monorepo-using-github-actions-4hij

name: publish

on:
  [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    - name: Install modules
      run: yarn
    - name: "Version and publish"
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
      run: |
        npm config set @threekit-tools:registry https://registry.npmjs.org/
        npm config set //registry.npmjs.org/:_authToken ${NPM_AUTH_TOKEN}

        if [ ${{ github.base_ref }} = main ]; then
          lerna version --conventional-commits --no-changelog --no-private --conventional-graduate --yes
        else
          lerna version --conventional-commits --no-changelog --no-private --conventional-prerelease --preid ${{ github.base_ref }} --yes
        fi

        lerna publish from-git --yes
